# Generated by Django 6.0 on 2026-01-02 20:54

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام هتل')),
                ('location', models.CharField(max_length=200, verbose_name='آدرس دقیق')),
                ('capacity', models.IntegerField(verbose_name='ظرفیت کل (نفر)')),
                ('is_approved', models.BooleanField(default=False, verbose_name='تایید شده توسط ادمین')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('user', 'گردشگر'), ('leader', 'تور لیدر'), ('admin', 'ادمین')], default='user', max_length=10, verbose_name='نقش')),
                ('phone_number', models.CharField(blank=True, max_length=15, verbose_name='شماره تماس')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='تصویر پروفایل')),
                ('national_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد ملی')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='اسلاگ')),
                ('content', models.TextField(verbose_name='متن کامل')),
                ('image', models.ImageField(upload_to='blog/', verbose_name='تصویر شاخص')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('is_published', models.BooleanField(default=True, verbose_name='منتشر شده')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'پست وبلاگ',
                'verbose_name_plural': 'پست\u200cهای وبلاگ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن نظر')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=True, verbose_name='تایید شده')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.post', verbose_name='پست')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان تور')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت (تومان)')),
                ('capacity', models.PositiveIntegerField(verbose_name='ظرفیت تور')),
                ('start_date', django_jalali.db.models.jDateField(verbose_name='تاریخ شروع')),
                ('duration_text', models.CharField(max_length=50, verbose_name='مدت زمان')),
                ('location', models.CharField(max_length=100, verbose_name='مکان برگزاری')),
                ('category', models.CharField(choices=[('تاریخی', 'تاریخی'), ('طبیعت گردی', 'طبیعت گردی'), ('فرهنگی', 'فرهنگی'), ('ماجراجویی', 'ماجراجویی')], max_length=20, verbose_name='دسته بندی')),
                ('description', models.TextField(verbose_name='توضیحات کامل')),
                ('image', models.ImageField(upload_to='tours/', verbose_name='تصویر تور')),
                ('is_active', models.BooleanField(default=False, verbose_name='تایید نهایی ادمین')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.hotel', verbose_name='هتل')),
                ('leader', models.ForeignKey(limit_choices_to={'role': 'leader'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='تورلیدر')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passengers_count', models.PositiveIntegerField(default=1, verbose_name='تعداد مسافر')),
                ('total_price', models.PositiveIntegerField(verbose_name='قیمت کل')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('confirmed', 'تایید شده (صدور بلیط)'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tour', verbose_name='تور')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن نظر')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='امتیاز')),
                ('is_approved', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.tour', verbose_name='تور')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TourLeaderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(default='نامشخص', max_length=100, verbose_name='تخصص')),
                ('experience_years', models.IntegerField(default=0, verbose_name='سال سابقه')),
                ('languages', models.CharField(default='فارسی', max_length=200, verbose_name='زبان\u200cها')),
                ('bio', models.TextField(default='پروفایل جدید', verbose_name='درباره من')),
                ('motivation', models.TextField(blank=True, null=True, verbose_name='انگیزه فعالیت')),
                ('documents', models.FileField(blank=True, null=True, upload_to='leader_docs/', verbose_name='فایل مدارک و رزومه')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تایید شده توسط مدیریت')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leader_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeaderReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='متن نظر')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='امتیاز')),
                ('is_approved', models.BooleanField(default=False, verbose_name='تایید شده توسط ادمین')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر نظر دهنده')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.tourleaderprofile', verbose_name='تور لیدر')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
